services:
  show-results-frontend:
    image: node:20
    command: |
      bash -c "
      sudo apt update &&
      sudo apt upgrade -y
      npm --prefix=./frontend install &&
      npm --prefix=./frontend run start
      "
    working_dir: /usr/share/app/show-results
    ports:
      - 3010:3010
    volumes:
      - ./show-results/frontend:./frontend
    networks:
      - default
  show-results-backend:
    image: node:20
    command: |
      bash -c "
      sudo apt update &&
      sudo apt upgrade -y
      npm --prefix=./backend install &&
      npm --prefix=./backend run start
      "
    working_dir: /usr/share/app/show-results
    ports:
      - 8090:8090
    volumes:
      - ./show-results/backend:./backend
    networks:
      - default

networks:
  default:
    driver: bridge