version: '3.8'

services:
  enterdata:
    image: ubuntu
    command: >
      bash -c "
      apt-get update &&
      apt-get upgrade -y &&
      apt-get install -y curl unzip &&
      curl -fsSL https://fnm.vercel.app/install | bash &&
      source ~/.bashrc &&
      export PATH=\"/root/.local/share/fnm:$PATH\" &&
      eval \"$(fnm env)\" &&
      fnm use --install-if-missing 20 &&
      apt-get install -y npm &&
      npm --prefix /usr/share/app/enter-data/backend install &&
      npm --prefix /usr/share/app/enter-data/frontend install &&
      npm --prefix /usr/share/app/enter-data/backend run start &&
      npm --prefix /usr/share/app/enter-data/frontend run start
      "
    ports:
      - 8000:8000
    working_dir: /usr/share/app
    volumes:
      - ./enter-data:/usr/share/app
    networks:
      - default

# MySQL service
#   mysql:
#     image: mysql:latest
#     volumes:
#       - mysql_db:/var/lib/mysql
#     environment: 
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

# volumes:
#   mysql_db: