services:
  EnterData:
    image: ubuntu
    command: <<EOF
    apt-get update -y
    apt-get upgrade -y
    ufw allow 443
    ufw allow 80
    ufw enable
    curl -fsSL https://fnm.vercel.app/install | bash
    source ~/.bashrc
    fnm use --install-if-missing 20
    npm --prefix /EnterData/src/server.js run start
    EOF
    ports:
      - 8000:8000
    working_dir: /EnterData
    volumes:
      - ./src:/usr/share/app
    networks:
      - default

  MySQL:
    image: ubuntu
    command: <<EOF
    apt-get update -y
    apt-get upgrade -y
    ufw allow 3306
    ufw enable
    apt-get install mysql-server -y
    mysql_secure_installation
    EOF
    ports:
      - 3306:3306
    working_dir: /SQL_Database
    volumes:
      - ./src:/usr/share/app
    networks:
      - default


networks:
  default:
    driver: bridge