services:
  frontend:
    image: node:20
    build: /enter-data/frontend/
    command: |
      bash -c "
      apt-get update &&
      apt-get upgrade -y &&
      npm --prefix /usr/share/app/enter-data/frontend install &&
      npm --prefix /usr/share/app/enter-data/frontend run build &&
      npm --prefix /usr/share/app/enter-data/frontend run start
      "
    ports:
      - 80:3000
    working_dir: /usr/share/app/enter-data
    volumes:
      - ./enter-data/frontend/:/usr/share/app/enter-data/frontend/
    networks:
      - default
  backend:
    image: node:20
    command: |
      bash -c "
      apt-get update &&
      apt-get upgrade -y &&
      npm --prefix /usr/share/app/enter-data/backend install &&
      npm --prefix /usr/share/app/enter-data/backend run start
      "
    ports:
      - 8080:8080
    working_dir: /usr/share/app/enter-data
    volumes:
      - ./enter-data/backend:/usr/share/app/enter-data/backend
    networks:
      - default
  mongodb:
    image: mongodb/mongodb-community-server:latest
    command:
    working_dir: /
    volumes:
      - mongodb_data:/data/db
    networks:
      - database

networks:
  default:
    driver: bridge
  database:
    driver: custom-driver

volumes:
  mongodb_data: