services:
  show-results-frontend:
    image: node:20
    command: |
      bash -c "
      sudo apt update &&
      sudo apt upgrade -y
      npm --prefix=./frontend install &&
      npm --prefix=./frontend run start
      "
    working_dir: /usr/share/app/show-results
    ports:
      - 3010:3010
    expose:
      - 3010
    volumes:
      - ./show-results/frontend:/usr/share/app/show-results/frontend
    networks:
      - default
  show-results-backend:
    image: node:20
    command: |
      bash -c "
      sudo apt update &&
      sudo apt upgrade -y
      npm --prefix=./backend install &&
      npm --prefix=./backend run start
      "
    working_dir: /usr/share/app/show-results
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
    ports:
      - 8090:8090
    volumes:
      - ./show-results/backend:/usr/share/app/show-results/backend
    networks:
      - default
  mongodb-db:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    working_dir: /
    ports:
     - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - database

networks:
  default:
    driver: bridge
  database:
    driver: bridge
    internal: true

volumes:
  mongodb_data:
