apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: kodymills395/auth-service:latest
        ports:
        - containerPort: 9088
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: google-secret
              key: PORT
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: google-secret
              key: HOST
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-secret
              key: GOOGLE_CLIENT_SECRET
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-endpoint
              key: backend-port