apiVersion: v1
kind: Pod
metadata:
  name: show-results-frontend
  labels:
    app_name: finanylizer
    environment: production
    layer: frontend
spec:
  containers:
    - name: show-results-frontend
      image: kodymills395/show-results-frontend:v1
      ports:
        - containerPort: 3010
