apiVersion: v1
kind: Secret
metadata:
  name: google-secret
type: Opaque
data:
  GOOGLE_CLIENT_ID: NDEyMjYyMDI3MDUtN2hkYjE4bnVuamdqYzZlOWdlODZzNDlyM2ZrdGY5bDUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=
  GOOGLE_CLIENT_SECRET: R09DU1BYLU1RRi1GV3VGcDg2eXNEaWg0Wkdsa3ZWV05Xc2Q=
  PORT: OTA4OA==
  HOST: MC4wLjAuMA==