apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: finanylizer-hpa
spec:
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  scaleTargetRef:
    apiVersion: apps:/v1
    kind: StatefulSet
    name: finanylizer
