apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storageclass
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4
