apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  labels:
    app_name: finanylizer
    tier: staging
    environment: production
    service_name: analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app_name: finanylizer
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app_name: finanylizer
        tier: staging
        environment: production
        service_name: analytics
    spec:
      containers:
        - name: analytics
          image: kodymills395/analyzer:latest
          ports:
            - containerPort: 10000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: db-port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: db-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: db-name
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
