apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    service_name: mysql-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app_name: finanylizer
      tier: database
      environment: production
      service_name: mysql
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app_name: finanylizer
        tier: database
        environment: production
        service_name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: db-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: db-password
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-host
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-port
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-database
            - name: INVESTMENT_ENUM
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: investment-enum
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mysql-storageclass
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storageclass
          persistentVolumeClaim:
            claimName: mysql-pvc
