apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-results-frontend-deployment
  labels:
    app_name: finanylizer
    tier: frontend
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app_name: finanylizer
      tier: frontend
      environment: production
      service_name: show-results-frontend
  template:
    metadata:
      labels:
        app_name: finanylizer
        tier: frontend
        environment: production
        service_name: show-results-frontend
    spec:
      containers:
        - name: show-results-frontend
          image: kodymills395/show-results-frontend:v1
          ports:
            - containerPort: 3010
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
