apiVersion: v1
kind: Service
metadata:
  name: mdb-service
spec:
  selector:
    app_name: finanylizer
    service_name: mdb-svc
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
