apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    service_name: enter-data-frontend
