apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: enter-data-frontend-hpa
spec:
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: enter-data-deployment
