apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: show-results-frontend-hpa
spec:
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: show-results-frontend-deployment